; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32G431CB]
platform = ststm32
board = genericSTM32G431CB
framework = arduino
debug_tool = cmsis-dap
upload_protocol = dfu
build_flags =
  -D HSE_VALUE=8000000
  ;Configuración para el uso del USB 
	-D USBCON
	-D HAL_PCD_MODULE_ENABLED
	-D USBD_USE_CDC
  -D USBD_CDC_RX_DATA_SIZE=512
  -D USBD_CDC_TX_DATA_SIZE=1024
  -D USBD_CDC_POLLING_INTERVAL=1
  -D USBD_IRQ_PRIO=5
	-D PIO_FRAMEWORK_ARDUINO_NANOLIB_FLOAT_PRINTF
  ;Configuración para el uso del ADC y TIM
  -D HAL_ADC_MODULE_ONLY
  -D HAL_DAC_MODULE_ONLY
  -D HAL_TIM_MODULE_ONLY
  -D USE_HAL_ADC_REGISTER_CALLBACKS
  -D USE_HAL_TIM_REGISTER_CALLBACKS
  -D USE_HAL_DAC_REGISTER_CALLBACKS
  ; Comunitacion y tiempo de protección 
  -D COMUNICACION
  -D METRICA
  -D APAGADO_ACELERACION_MS=600
